services:
  mariadb:
    image: mariadb:11.2
    container_name: mariadb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: digita45_digital_arena
      MYSQL_USER: database
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - /tmp/shared:/shared 

volumes:
  mariadb_data:
